/* Recipes transcribed from the photographed cookbook pages.
   Ingredient tuple: [item, qty, unit, line]
   - item/qty/unit are in shopping units, used to merge the grocery list (qty null = to taste / already on hand)
   - line is the wording shown on the recipe page; null hides the row (used for sub-recipe components) */
const COURSES = ['Drinks', 'Snacks', 'Salads', 'Soups', 'Mains', 'Seafood', 'Veggie Mains', 'Sides', 'Brunch'];

const RECIPES = [
// ---------- Drinks ----------
{ id: 'paloma-punch', name: 'Spicy Paloma Punch', course: 'Drinks', serves: '12 to 14 drinks', page: 22, img: '0513', ingredients: [
  ['grapefruit', 8, '', '4 cups fresh grapefruit juice (about 8 grapefruits)'],
  ['tequila', 1, 'bottle', '1 (750 ml) bottle blanco tequila'],
  ['lime', 7, '', '¾ cup fresh lime juice (6 to 8 limes)'],
  ['jalapeño', 2, '', '¾ cup Jalapeño Simple Syrup (half batch: 2 jalapeños, ½ cup sugar)'],
  ['sugar', 0.5, 'cup', null],
  ['grapefruit', 1, '', '1 grapefruit, thinly sliced'],
  ['lime', 1, '', '1 lime, thinly sliced'],
  ['sparkling water', 1.5, 'cup', '1½ cups sparkling water, chilled'],
  ['candied jalapeños', 1, 'jar', '12 to 14 candied jalapeño slices, for garnish'],
  ['ice', null, '', 'Ice, for serving']],
  steps: ['In a large pitcher, stir together the grapefruit juice, tequila, lime juice, and jalapeño syrup. Chill until ready to serve.',
    'Add the grapefruit and lime slices and a few handfuls of ice, then top with the sparkling water.',
    'Pour into ice-filled glasses and garnish each with a candied jalapeño slice.'] },
{ id: 'jalapeno-syrup', name: 'Jalapeño Simple Syrup', course: 'Drinks', serves: 'About 1½ cups', page: 25, img: '0514', ingredients: [
  ['jalapeño', 4, '', '1 cup thinly sliced jalapeños (3 to 4 peppers)'],
  ['sugar', 1, 'cup', '1 cup granulated sugar'],
  ['water', null, '', '1 cup water']],
  steps: ['Bring the water and jalapeños to a boil in a small saucepan.',
    'Lower the heat, add the sugar, and simmer, stirring, until dissolved, about 5 minutes.',
    'Let cool for 1 hour, then strain out the jalapeños. Store the syrup in a jar in the refrigerator.'] },
{ id: 'old-fashioned', name: 'Cider & Bourbon Old-Fashioned', course: 'Drinks', serves: '2', page: 30, img: '0518', ingredients: [
  ['apple cider', 0.5, 'cup', '½ cup fresh apple cider'],
  ['bourbon', 0.5, 'cup', '½ cup bourbon'],
  ['maple syrup', 1, 'tsp', '1 teaspoon pure maple syrup'],
  ['bitters', null, '', '4 dashes Angostura bitters'],
  ['orange', 1, '', '2 strips orange peel'],
  ['ice', null, '', 'Ice']],
  steps: ['Combine the cider, bourbon, maple syrup, and bitters in a cocktail shaker or mixing glass with ice.',
    'Stir until well chilled, about 30 seconds.',
    'Strain into two rocks glasses over fresh ice and garnish each with a strip of orange peel.'] },
{ id: 'beach-water', name: 'Beach Water', course: 'Drinks', serves: '8', page: 34, img: '0520', ingredients: [
  ['coconut water', 16.9, 'oz', '1 (16.9-ounce) bottle coconut water'],
  ['vodka', 0.5, 'cup', '½ cup vodka'],
  ['salt', null, '', '⅛ teaspoon kosher salt'],
  ['mint', 0.5, 'bunch', '½ cup fresh mint leaves, plus sprigs for garnish'],
  ['ice', null, '', 'Ice']],
  steps: ['In a pitcher, stir together the coconut water, vodka, and salt.',
    'Lightly bruise the mint leaves and add them to the pitcher. Chill until cold.',
    'Serve over ice, garnished with mint sprigs.'] },
{ id: 'gin-martini', name: 'Gin Martini with Rosemary & Grapefruit', course: 'Drinks', serves: '2', page: 38, img: '0521', ingredients: [
  ['gin', 0.5, 'cup', '½ cup gin'],
  ['grapefruit', 1, '', '¼ cup fresh grapefruit juice (1 grapefruit), plus 2 twists'],
  ['dry vermouth', 2, 'tbsp', '2 tablespoons dry vermouth'],
  ['rosemary', 1, 'bunch', 'Fresh rosemary sprigs, for garnish'],
  ['ice', null, '', 'Ice']],
  steps: ['Fill a cocktail shaker with ice. Add the gin, grapefruit juice, and vermouth.',
    'Stir or shake until very cold.',
    'Strain into two chilled martini glasses and garnish with a grapefruit twist and a rosemary sprig.'] },
{ id: 'garibaldi', name: 'Garibaldi Spritz', course: 'Drinks', serves: '8', page: 42, img: '0523', ingredients: [
  ['orange', 8, '', '2 cups fresh orange juice (about 8 oranges)'],
  ['campari', 0.5, 'cup', '½ cup Campari'],
  ['sparkling water', 2, 'cup', '2 cups sparkling water or Prosecco'],
  ['orange', 1, '', '8 orange slices, for garnish'],
  ['ice', null, '', 'Ice']],
  steps: ['Whisk the orange juice vigorously (or blend briefly) so it gets frothy.',
    'Stir in the Campari.',
    'Pour over ice, top with sparkling water or Prosecco, and garnish with orange slices.'] },

// ---------- Snacks ----------
{ id: 'beet-dip', name: 'Golden Beet Dip with Yogurt & Tahini', course: 'Snacks', serves: 'About 1 pint', page: 26, img: '0516', ingredients: [
  ['golden beets', 1, 'lb', '1 pound golden beets (about 6 medium)'],
  ['olive oil', 1, 'tbsp', '1 tablespoon extra-virgin olive oil, plus more'],
  ['garlic', 1, 'clove', '1 garlic clove'],
  ['greek yogurt', 0.5, 'cup', '½ cup plain Greek yogurt'],
  ['tahini', 0.25, 'cup', '¼ cup tahini'],
  ['lemon', 1, '', '2 tablespoons fresh lemon juice (1 lemon)'],
  ['maple syrup', 2, 'tsp', '2 teaspoons pure maple syrup'],
  ['salt', null, '', '1¼ teaspoons kosher salt'],
  ['turmeric', 0.25, 'tsp', '¼ teaspoon ground turmeric'],
  ['cayenne', null, '', 'Pinch of cayenne (optional)'],
  ['mint', 0.25, 'bunch', 'Fresh mint, for serving'],
  ['pita', 1, 'pack', 'Pita or crudités, for serving']],
  steps: ['Heat the oven to 400°F. Wrap the beets in a foil packet with a drizzle of oil and roast until tender, 45 to 60 minutes.',
    'When cool enough to handle, rub off the skins and cut the beets into chunks.',
    'In a food processor, blend the beets, garlic, yogurt, tahini, lemon juice, maple syrup, salt, turmeric, and cayenne until smooth.',
    'Spoon into a bowl, drizzle with oil, top with mint, and serve with pita or crudités.'] },
{ id: 'baked-harbison', name: 'Baked Harbison', course: 'Snacks', serves: '4 to 6', page: 29, img: '0517', ingredients: [
  ['harbison cheese', 9, 'oz', '1 (9-ounce) wheel Harbison cheese'],
  ['white wine', 1, 'tbsp', '1 tablespoon dry white wine'],
  ['kirsch', 1, 'tbsp', '1 tablespoon kirsch'],
  ['salt', null, '', 'Kosher salt'],
  ['nutmeg', null, '', 'Whole nutmeg, for grating'],
  ['pink peppercorns', null, '', 'Crushed pink peppercorns (optional)'],
  ['baguette', 1, '', 'Sliced baguette, for serving']],
  steps: ['Heat the oven to 375°F.',
    'Cut away the top rind of the cheese, leaving it in its wooden band, and set it on a sheet pan.',
    'Pour the wine and kirsch over the top and sprinkle with a little salt.',
    'Bake until molten, 15 to 20 minutes. Grate nutmeg over the top, scatter with pink peppercorns, and serve hot with baguette.'] },
{ id: 'cashews', name: 'Honey-Roasted Cashews with a Kick', course: 'Snacks', serves: 'About 4 cups', page: 33, img: '0519', ingredients: [
  ['eggs', 2, '', '2 large egg whites'],
  ['brown sugar', 0.5, 'cup', '½ cup light brown sugar'],
  ['honey', 2, 'tbsp', '2 tablespoons honey'],
  ['butter', 2, 'tbsp', '2 tablespoons unsalted butter, melted'],
  ['salt', null, '', '1 teaspoon kosher salt'],
  ['cayenne', 0.25, 'tsp', '¼ teaspoon cayenne pepper'],
  ['cashews', 1, 'lb', '1 pound roasted unsalted cashews'],
  ['flaky salt', null, '', 'Flaky sea salt']],
  steps: ['Heat the oven to 350°F and line a sheet pan with parchment.',
    'Whisk the egg whites until frothy, then whisk in the brown sugar, honey, butter, salt, and cayenne.',
    'Add the cashews and toss to coat, then spread on the pan.',
    'Roast for 20 to 25 minutes, tossing every 10 minutes, until glossy and golden. Sprinkle with flaky salt and let cool completely.'] },
{ id: 'crab-dip', name: 'Baked Crab Dip with Sweet Corn & Old Bay', course: 'Snacks', serves: '6', page: 41, img: '0522', ingredients: [
  ['scallions', 2, '', '1 to 2 scallions, thinly sliced'],
  ['olive oil', 0.5, 'tbsp', '½ tablespoon extra-virgin olive oil'],
  ['corn', 1, 'ear', '½ cup fresh corn kernels (1 ear)'],
  ['jalapeño', 0.5, '', '2 tablespoons minced jalapeño (½ pepper)'],
  ['cream cheese', 4, 'oz', '4 ounces cream cheese, softened'],
  ['parmesan', 2, 'oz', '½ cup plus 2 tablespoons grated Parmesan'],
  ['mayonnaise', 3, 'tbsp', '3 tablespoons mayonnaise'],
  ['lemon', 0.33, '', '1 tablespoon fresh lemon juice'],
  ['old bay', 0.5, 'tsp', '½ teaspoon Old Bay seasoning'],
  ['salt', null, '', '½ teaspoon kosher salt'],
  ['crab', 8, 'oz', '8 ounces lump crabmeat, picked over'],
  ['crackers', 1, 'box', 'Cucumber slices and crackers, for serving']],
  steps: ['Heat the oven to 375°F.',
    'Cook the scallion whites, corn, and jalapeño in the oil over medium heat until just tender, 3 to 4 minutes. Let cool.',
    'Mix the cream cheese, ½ cup Parmesan, mayonnaise, lemon juice, Old Bay, and salt until smooth. Fold in the vegetables and crab.',
    'Spread in a 1-quart baking dish, top with the remaining Parmesan, and bake until bubbling and golden, about 25 minutes. Top with scallion greens and serve warm.'] },
{ id: 'cherry-salsa', name: 'Cherry, Nectarine & Jalapeño Salsa', course: 'Snacks', serves: 'About 3 cups', page: 45, img: '0524', ingredients: [
  ['nectarines', 2, '', '2 ripe nectarines, diced'],
  ['cherries', 2, 'cup', '2 cups sweet cherries, pitted and quartered'],
  ['red onion', 0.25, '', '¼ cup minced red onion'],
  ['jalapeño', 1, '', '3 tablespoons minced jalapeño (1 large)'],
  ['lime', 0.5, '', '1 tablespoon fresh lime juice'],
  ['salt', null, '', '½ teaspoon kosher salt'],
  ['basil', 0.5, 'bunch', '½ cup chopped fresh basil or cilantro'],
  ['tortilla chips', 1, 'bag', 'Tortilla chips, for serving']],
  steps: ['In a medium bowl, combine the nectarines, cherries, red onion, and jalapeño.',
    'Add the lime juice and salt and toss gently.',
    'Fold in the herbs just before serving with tortilla chips.'] },

// ---------- Salads ----------
{ id: 'kale-salad', name: 'Kale Salad with Gouda, Honeycrisp & Walnuts', course: 'Salads', serves: '4', page: 50, img: '0525', ingredients: [
  ['walnuts', 1, 'cup', '1 cup walnuts'],
  ['kale', 1, 'bunch', '1 bunch curly kale (8 to 10 ounces)'],
  ['olive oil', 0.25, 'cup', '¼ cup plus 1 teaspoon extra-virgin olive oil'],
  ['cider vinegar', 2, 'tbsp', '2 tablespoons apple cider vinegar'],
  ['maple syrup', 1, 'tsp', '1 teaspoon pure maple syrup'],
  ['dijon mustard', 0.5, 'tsp', '½ teaspoon Dijon mustard'],
  ['salt', null, '', '½ teaspoon kosher salt'],
  ['black pepper', null, '', 'Freshly ground black pepper'],
  ['apples', 1, '', '1 Honeycrisp apple, thinly sliced'],
  ['gouda', 2, 'oz', '¾ cup shaved aged Gouda (2 ounces)']],
  steps: ['Heat the oven to 350°F. Toast the walnuts on a sheet pan until fragrant, about 10 minutes, then chop.',
    'Strip the kale from its stems and tear into pieces. Massage with 1 teaspoon oil for 30 seconds until slightly softened.',
    'Whisk the vinegar, maple syrup, mustard, salt, pepper, and remaining ¼ cup oil.',
    'Toss the kale with the dressing, apple, walnuts, and Gouda.'] },
{ id: 'carrot-salad', name: 'Shaved Carrot Salad with Creamy Sesame-Ginger Dressing', course: 'Salads', serves: '4 to 6', page: 54, img: '0527', ingredients: [
  ['tahini', 3, 'tbsp', '3 tablespoons tahini'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['seasoned rice vinegar', 3, 'tbsp', '3 tablespoons seasoned rice vinegar'],
  ['ginger', 0.25, 'knob', '2 teaspoons grated fresh ginger'],
  ['soy sauce', 1, 'tsp', '1 teaspoon soy sauce'],
  ['garlic', 1, 'clove', '1 small garlic clove, grated'],
  ['salt', null, '', '½ teaspoon kosher salt'],
  ['carrots', 1.5, 'lb', '1½ pounds carrots, peeled'],
  ['scallions', 3, '', '½ cup thinly sliced scallions (2 to 3)'],
  ['sesame seeds', 1, 'tsp', '1 teaspoon toasted sesame seeds']],
  steps: ['Whisk the tahini, oil, vinegar, ginger, soy sauce, garlic, salt, and 1 tablespoon cold water until creamy.',
    'Use a vegetable peeler to shave the carrots into long ribbons.',
    'Toss the carrots with the dressing and most of the scallions.',
    'Top with the remaining scallions and the sesame seeds.'] },
{ id: 'escarole-salad', name: 'Escarole Salad with Cara Cara Oranges, Marcona Almonds & Goat Cheese', course: 'Salads', serves: '4 to 6', page: 57, img: '0528', ingredients: [
  ['escarole', 1, 'head', '1 head escarole (14 to 16 ounces)'],
  ['olive oil', 0.25, 'cup', '¼ cup extra-virgin olive oil'],
  ['sherry vinegar', 1, 'tbsp', '1 tablespoon sherry vinegar'],
  ['honey', 1, 'tbsp', '1 tablespoon honey'],
  ['dijon mustard', 0.5, 'tsp', '½ teaspoon Dijon mustard'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['shallot', 0.25, '', '1 tablespoon minced shallot'],
  ['orange', 2, '', '2 Cara Cara oranges'],
  ['marcona almonds', 0.5, 'cup', '½ cup Marcona almonds'],
  ['goat cheese', 2, 'oz', '2 ounces goat cheese, crumbled']],
  steps: ['Tear the escarole into bite-size pieces, wash, and dry well.',
    'Whisk the vinegar, honey, mustard, shallot, salt, and pepper, then whisk in the oil.',
    'Peel the oranges, removing the pith, and slice into rounds.',
    'Toss the escarole with the dressing, then top with the oranges, almonds, and goat cheese.'] },
{ id: 'taverna-salad', name: 'Taverna Salad', course: 'Salads', serves: '4 to 6', page: 58, img: '0529', ingredients: [
  ['olive oil', 0.25, 'cup', '¼ cup extra-virgin olive oil, plus more'],
  ['red wine vinegar', 2, 'tbsp', '2 tablespoons red wine vinegar'],
  ['garlic', 1, 'clove', '1 teaspoon minced garlic (1 clove)'],
  ['dried oregano', 0.5, 'tsp', '½ teaspoon dried oregano'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['cherry tomatoes', 0.5, 'pint', '3 tomatoes or 1 cup cherry tomatoes'],
  ['chickpeas', 1, 'can', '1 (15-ounce) can chickpeas, drained'],
  ['bell pepper', 1, '', '1 orange or yellow bell pepper'],
  ['cucumber', 0.5, '', '½ English cucumber (about 1½ cups diced)'],
  ['kalamata olives', 0.5, 'cup', '½ cup pitted Kalamata olives'],
  ['parsley', 0.25, 'bunch', '¼ cup chopped fresh parsley'],
  ['red onion', 0.25, '', '¼ cup minced red onion or shallot'],
  ['capers', 2, 'tbsp', '2 tablespoons capers'],
  ['scallions', 2, '', '2 scallions, sliced'],
  ['pita', 1, '', '1 (6-inch) pita'],
  ['halloumi', 8, 'oz', '8 ounces halloumi']],
  steps: ['Whisk the oil, vinegar, garlic, oregano, salt, and pepper.',
    'Chop the vegetables and toss with the chickpeas, olives, parsley, onion, capers, scallions, and dressing.',
    'Brush the pita with oil and toast in a skillet until crisp, about 5 minutes. Tear into pieces.',
    'Slice the halloumi and sear in the skillet until golden, 2 to 3 minutes per side. Top the salad with the halloumi and pita.'] },
{ id: 'fennel-beans', name: 'Marinated Fennel & Green Bean Salad', course: 'Salads', serves: '6', page: 61, img: '0530', ingredients: [
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['green beans', 1, 'lb', '1 pound haricots verts, trimmed'],
  ['olive oil', 0.25, 'cup', '¼ cup extra-virgin olive oil'],
  ['orange', 0.5, '', 'Zest of ½ orange plus 2 tablespoons juice'],
  ['lemon', 0.5, '', 'Zest of ½ lemon plus 1 tablespoon juice'],
  ['dijon mustard', 0.5, 'tsp', '½ teaspoon Dijon mustard'],
  ['shallot', 1, '', '¼ cup thinly sliced shallot (1 large)'],
  ['fennel', 1, 'bulb', '1 medium fennel bulb (about 8 ounces)'],
  ['kalamata olives', 0.5, 'cup', '½ cup pitted Kalamata olives'],
  ['parsley', 0.25, 'bunch', 'Fennel fronds or fresh parsley, for serving']],
  steps: ['Blanch the green beans in salted boiling water until crisp-tender, 3 to 5 minutes, then plunge into ice water and drain.',
    'Whisk the oil, citrus zest and juice, mustard, salt, and pepper. Stir in the shallot.',
    'Thinly shave the fennel and toss with the beans, olives, and dressing.',
    'Marinate for at least 1 hour or up to 6. Top with fennel fronds or parsley before serving.'] },
{ id: 'little-gem', name: 'Little Gem Salad with Avocado Goddess Dressing & Pickled Red Onions', course: 'Salads', serves: '4', page: 65, img: '0532', ingredients: [
  ['garlic', 1, 'clove', '1 teaspoon chopped garlic (1 clove)'],
  ['dill', 0.25, 'bunch', '3 tablespoons chopped fresh dill'],
  ['chives', 0.25, 'bunch', '2 tablespoons chopped chives or scallions'],
  ['avocado', 1, '', '1 ripe Hass avocado'],
  ['mayonnaise', 0.33, 'cup', '⅓ cup mayonnaise'],
  ['lemon', 1, '', '3 tablespoons fresh lemon juice (1 large lemon)'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['little gem lettuce', 12, 'oz', '12 ounces Little Gem lettuce'],
  ['red onion', 0.5, '', '½ cup quick-pickled red onions']],
  steps: ['Blend the garlic, dill, chives, avocado, mayonnaise, lemon juice, 1 teaspoon salt, and a splash of water until smooth.',
    'Separate the Little Gem leaves, wash, and dry.',
    'Arrange the leaves on a platter and spoon the dressing over them.',
    'Top with pickled red onions and black pepper.'] },
{ id: 'celery-waldorf', name: 'Celery Waldorf with Pickled Golden Raisins', course: 'Salads', serves: '6', page: 69, img: '0533', ingredients: [
  ['golden raisins', 0.5, 'cup', '½ cup golden raisins'],
  ['white wine vinegar', 4, 'tbsp', '4 tablespoons white wine or Champagne vinegar, divided'],
  ['butter', 1, 'tbsp', '1 tablespoon unsalted butter'],
  ['maple syrup', 2, 'tbsp', '2 tablespoons pure maple syrup'],
  ['walnuts', 1, 'cup', '1 cup walnuts'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['celery', 1, 'bunch', '1 large bunch celery (about 1½ pounds)'],
  ['apples', 1, '', '1 large Honeycrisp or Fuji apple'],
  ['parsley', 0.25, 'bunch', '¼ cup chopped fresh parsley'],
  ['olive oil', 5, 'tbsp', '5 tablespoons extra-virgin olive oil'],
  ['blue cheese', 4, 'oz', '1 cup crumbled blue cheese (4 ounces)']],
  steps: ['Simmer the raisins with 2 tablespoons vinegar for 2 minutes, then let them plump off the heat.',
    'Melt the butter with the maple syrup, add the walnuts, and cook until glazed, 3 to 5 minutes. Season with salt and cool.',
    'Thinly slice the celery and apple. Whisk the remaining vinegar with the oil, salt, and pepper.',
    'Toss the celery, apple, parsley, and raisins with the dressing, then top with the walnuts and blue cheese.'] },
{ id: 'arugula-romaine', name: 'Arugula and Romaine Salad with Radish, Shaved Parm, Pistachios & Mint', course: 'Salads', serves: '6 to 8', page: 73, img: '0535', ingredients: [
  ['arugula', 2.5, 'oz', '4 cups baby arugula (about half a 5-ounce box)'],
  ['romaine', 1, 'heart', '1 romaine heart, sliced crosswise into ½-inch ribbons'],
  ['radishes', 1, 'bunch', '1 bunch radishes (about 6)'],
  ['pistachios', 0.5, 'cup', '½ cup salted roasted pistachios, chopped'],
  ['parmesan', 3, 'oz', '1 cup shaved pecorino or Parmesan (3 ounces)'],
  ['lemon', 0.67, '', '2 tablespoons fresh lemon juice'],
  ['salt', null, '', '½ teaspoon kosher salt'],
  ['black pepper', null, '', 'Freshly ground black pepper'],
  ['olive oil', 0.25, 'cup', '¼ cup extra-virgin olive oil'],
  ['mint', 1, 'bunch', '½ cup fresh mint leaves (1 bunch)']],
  steps: ['Combine the arugula and romaine in a large shallow bowl. Slice the radishes paper-thin and add them with the pistachios and cheese.',
    'Whisk the lemon juice, salt, and pepper, then slowly whisk in the oil.',
    'Just before serving, pour the dressing over the salad and toss. Tear the mint over the top, toss again, and serve.'] },
{ id: 'radicchio-salad', name: 'Radicchio Salad with Pear, Cornbread Crumbs & Bacon', course: 'Salads', serves: '4 to 6', page: 77, img: '0537', ingredients: [
  ['cornbread', 4.5, 'oz', '2 cups coarsely crumbled cornbread or corn muffin'],
  ['olive oil', 0.33, 'cup', '⅓ cup plus 1 tablespoon extra-virgin olive oil'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['bacon', 8, 'oz', '8 ounces thick-cut bacon'],
  ['radicchio', 1, 'head', '1 large (10-ounce) head radicchio'],
  ['red wine vinegar', 2, 'tbsp', '2 tablespoons red wine vinegar'],
  ['shallot', 0.25, '', '1 tablespoon minced shallot'],
  ['whole-grain mustard', 1, 'tsp', '1 teaspoon whole-grain mustard'],
  ['honey', 1, 'tsp', '1 teaspoon honey'],
  ['pear', 1, '', '1 firm, ripe Anjou pear, thinly sliced']],
  steps: ['Heat the oven to 400°F. Toss the cornbread crumbs with 1 tablespoon oil and a pinch of salt and bake until golden, 10 to 15 minutes.',
    'Bake the bacon on a foil-lined sheet pan until crisp, 20 to 25 minutes. Chop.',
    'Tear the radicchio into bite-size pieces. Whisk the vinegar, shallot, mustard, honey, salt, and pepper, then the remaining oil.',
    'Toss the radicchio with the dressing, then add the cornbread, bacon, and pear and toss gently.'] },
{ id: 'tomato-peach', name: 'Tomato and Peach Salad with Toasted Farro & Mozzarella', course: 'Salads', serves: '4', page: 78, img: '0538', ingredients: [
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['farro', 0.5, 'cup', '½ cup pearled farro, rinsed'],
  ['olive oil', 4, 'tbsp', '4 tablespoons extra-virgin olive oil, divided'],
  ['cherry tomatoes', 1, 'pint', '1 pint cherry tomatoes, halved'],
  ['peaches', 2, '', '2 peaches or nectarines, cut into wedges'],
  ['mozzarella', 4, 'oz', '4 ounces fresh mozzarella, torn'],
  ['white wine vinegar', 1, 'tbsp', '1 tablespoon Champagne or white wine vinegar'],
  ['mint', 0.5, 'bunch', '¼ cup fresh mint or basil leaves, chopped']],
  steps: ['Simmer the farro in salted water until tender, about 30 minutes. Drain well and cool.',
    'Heat the oven to 375°F. Toss the farro with 1 tablespoon oil and a pinch of salt and toast on a sheet pan until crisp at the edges, 15 to 20 minutes.',
    'Spread half the farro on a platter and arrange the tomatoes, peaches, and mozzarella on top.',
    'Whisk the vinegar with the remaining oil and a pinch of salt. Drizzle over the salad and top with the rest of the farro and the herbs.'] },

// ---------- Soups ----------
{ id: 'ratatouille-soup', name: 'Ratatouille Lentil Soup', course: 'Soups', serves: '6 to 8', page: 53, img: '0526', ingredients: [
  ['olive oil', 5, 'tbsp', '5 tablespoons extra-virgin olive oil'],
  ['eggplant', 1, '', '1 pound eggplant (1 medium), diced'],
  ['yellow onion', 1, '', '1 yellow onion, diced'],
  ['zucchini', 2, '', '1 pound zucchini (2 medium), diced'],
  ['garlic', 4, 'clove', '2 tablespoons minced garlic (4 cloves)'],
  ['dried oregano', 1, 'tsp', '1 teaspoon dried oregano'],
  ['tomato paste', 2, 'tbsp', '2 tablespoons tomato paste'],
  ['vegetable broth', 8, 'cup', '8 cups vegetable broth'],
  ['crushed tomatoes', 1, 'can', '1 (14.5-ounce) can crushed tomatoes'],
  ['green lentils', 1, 'cup', '1 cup French green lentils'],
  ['roasted red peppers', 1, 'cup', '1 cup jarred roasted red peppers, chopped'],
  ['salt', null, '', '2 teaspoons kosher salt'],
  ['black pepper', null, '', '½ teaspoon black pepper'],
  ['basil', 0.5, 'bunch', '½ cup chopped fresh basil'],
  ['balsamic vinegar', 1, 'tbsp', '1 tablespoon balsamic vinegar']],
  steps: ['Heat the oil in a large pot. Cook the eggplant until browned, then add the onion and zucchini and cook until soft.',
    'Stir in the garlic, oregano, and tomato paste and cook for 1 minute.',
    'Add the broth, crushed tomatoes, lentils, roasted peppers, salt, and pepper. Bring to a boil, then simmer until the lentils are tender, 50 to 60 minutes.',
    'Stir in the basil and balsamic and adjust the seasoning.'] },
{ id: 'sausage-soup', name: 'Sausage and White Bean Soup with Swiss Chard & Skillet Croutons', course: 'Soups', serves: '6', page: 62, img: '0531', ingredients: [
  ['swiss chard', 1, 'bunch', '1 bunch Swiss chard (about 8 ounces)'],
  ['olive oil', 5, 'tbsp', '5 tablespoons extra-virgin olive oil, divided'],
  ['hot italian sausage', 1, 'lb', '1 pound hot Italian sausage, casings removed'],
  ['yellow onion', 1, '', '1 yellow onion, chopped'],
  ['garlic', 4, 'clove', '4 garlic cloves, minced'],
  ['white wine', 0.5, 'cup', '½ cup dry white wine'],
  ['cannellini beans', 1, 'can', '1 (15-ounce) can cannellini beans, drained'],
  ['chicken broth', 4, 'cup', '4 cups chicken broth'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['crusty bread', 4.5, 'oz', '3 cups ½-inch bread cubes (4½ ounces)'],
  ['parmesan', 1, 'oz', 'Grated Parmesan, for serving']],
  steps: ['Separate the chard stems and leaves; chop both.',
    'Brown the sausage in 2 tablespoons oil, breaking it up. Add the onion and chard stems and cook until soft, then the garlic for 1 minute.',
    'Add the wine and let it reduce, then the beans and broth. Simmer for 15 minutes and stir in the chard leaves until wilted.',
    'Toast the bread cubes in the remaining oil in a skillet until crisp. Serve the soup topped with croutons and Parmesan.'] },
{ id: 'gazpacho', name: 'Melon & Cucumber Gazpacho', course: 'Soups', serves: '4 to 6', page: 70, img: '0534', ingredients: [
  ['cucumber', 1, '', '1 large English cucumber (about 14 ounces)'],
  ['melon', 0.5, '', '4 cups diced cantaloupe or honeydew (½ of a 4-pound melon)'],
  ['cherry tomatoes', 0.5, 'pint', '1 cup orange or yellow cherry tomatoes'],
  ['jalapeño', 1, '', '2 tablespoons seeded, chopped jalapeño (1 small)'],
  ['red onion', 0.25, '', '¼ cup chopped red onion'],
  ['lime', 1.5, '', '2 tablespoons fresh lime juice (1 to 2 limes)'],
  ['white wine vinegar', 2, 'tbsp', '2 tablespoons white wine vinegar'],
  ['salt', null, '', '1½ teaspoons kosher salt'],
  ['olive oil', 0.25, 'cup', '¼ cup extra-virgin olive oil, plus more'],
  ['mint', 0.25, 'bunch', 'Fresh mint, basil, or cilantro, for serving']],
  steps: ['Roughly chop the cucumber.',
    'Blend the cucumber, melon, tomatoes, jalapeño, onion, lime juice, vinegar, and salt until smooth. With the blender running, drizzle in the oil.',
    'Chill for at least 2 hours.',
    'Serve cold with a drizzle of oil and torn herbs.'] },
{ id: 'avgolemono', name: 'Avgolemono-ish Chicken Noodle Soup', course: 'Soups', serves: '8 to 10', page: 74, img: '0536', ingredients: [
  ['chicken breasts', 1.5, 'lb', '2 bone-in, skin-on chicken breasts (12 ounces each)'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil, plus more'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['carrots', 0.5, 'lb', '1½ cups diced carrots (3 medium)'],
  ['celery', 0.25, 'bunch', '1½ cups diced celery (3 ribs)'],
  ['yellow onion', 1, '', '1 yellow onion, diced'],
  ['chicken broth', 12, 'cup', '12 cups low-sodium chicken broth'],
  ['ditalini', 1, 'cup', '1 cup ditalini or pearl couscous'],
  ['chickpeas', 1, 'can', '1 (15-ounce) can chickpeas, drained'],
  ['eggs', 3, '', '3 large egg yolks'],
  ['lemon', 2, '', '½ cup fresh lemon juice (2 lemons)'],
  ['baby spinach', 3, 'oz', '3 cups baby spinach'],
  ['dill', 0.25, 'bunch', '¼ cup chopped fresh dill or parsley']],
  steps: ['Heat the oven to 350°F. Rub the chicken with oil, salt, and pepper and roast until cooked through, 30 to 35 minutes. Shred, discarding skin and bones.',
    'Cook the carrots, celery, and onion in the oil in a large pot until soft. Add the broth and bring to a boil.',
    'Add the pasta and chickpeas and simmer until the pasta is tender.',
    'Whisk the yolks with the lemon juice, then slowly whisk in a ladle of hot broth to temper. Stir the mixture back into the pot with the chicken, spinach, and dill without letting it boil.'] },

// ---------- Mains (Chicken, Beef & Pork) ----------
{ id: 'cider-sausages', name: 'Cider-Glazed Sausages with Caramelized Apples & Fennel', course: 'Mains', serves: '4', page: 87, img: '0539', ingredients: [
  ['apples', 1, '', '1 medium Honeycrisp or Fuji apple'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil, divided'],
  ['fennel', 0.5, 'bulb', '1 cup thinly sliced fennel (about half a bulb)'],
  ['red onion', 0.5, '', '1 cup thinly sliced red onion (about half a large onion)'],
  ['maple syrup', 1, 'tbsp', '1 tablespoon pure maple syrup'],
  ['cider vinegar', 4, 'tbsp', '4 tablespoons apple cider vinegar, divided'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['sweet italian sausage', 1, 'lb', '4 sweet Italian sausage links (about 1 pound)'],
  ['apple cider', 0.75, 'cup', '¾ cup fresh apple cider'],
  ['parsley', 0.25, 'bunch', 'Chopped fresh parsley or fennel fronds, for serving']],
  steps: ['Core and thinly slice the apple, then cut the slices into thirds.',
    'In a 10-inch Dutch oven or deep skillet, heat 2 tablespoons oil over medium-low. Add the fennel, onion, apple, and maple syrup and cook, stirring occasionally, until lightly caramelized, about 15 minutes.',
    'Add 2 tablespoons vinegar and ½ teaspoon salt, scraping up any browned bits. Transfer to a bowl and wipe out the pan.',
    'Heat the remaining oil over medium-high and brown the sausages, 4 to 6 minutes. Lower the heat, add the cider, and simmer until the sausages are cooked through and the cider is reduced, 6 to 10 minutes.',
    'Return the apples and vegetables to the pan with the remaining vinegar. Toss, season, and serve with parsley.'] },
{ id: 'champagne-chicken', name: 'Champagne Chicken', course: 'Mains', serves: '3 to 4', page: 88, img: '0540', ingredients: [
  ['whole chicken', 1, '', '1 whole chicken (4 pounds), cut into 8 pieces'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['olive oil', 2, 'tbsp', '2 tablespoons extra-virgin olive oil'],
  ['yellow onion', 1, '', '1 large yellow onion, halved and sliced ¼ inch thick'],
  ['green grapes', 12, 'oz', '12 ounces seedless green grapes, in small clusters (about 2½ cups)'],
  ['garlic', 4, 'clove', '4 garlic cloves, minced'],
  ['thyme', 0.5, 'bunch', '2 teaspoons fresh thyme leaves, plus more for serving'],
  ['champagne', 0.5, 'cup', '½ cup Champagne or Prosecco'],
  ['dijon mustard', 1, 'tsp', '1 teaspoon Dijon mustard'],
  ['heavy cream', 2, 'tbsp', '2 tablespoons heavy cream']],
  steps: ['Heat the oven to 375°F. Pat the chicken dry and season with 1 teaspoon salt and ½ teaspoon pepper.',
    'In a 12-inch ovenproof skillet, heat the oil over medium. Brown the chicken skin-side down until golden, 6 to 8 minutes, then flip and brown the other side. Transfer to a plate.',
    'Pour off all but a thin layer of fat. Cook the onion with a pinch of salt until lightly browned, 8 to 10 minutes. Add the grapes, garlic, and thyme for 30 seconds.',
    'Add the Champagne and scrape up the browned bits. Nestle the chicken skin-side up on top and bake until the breast meat reaches 165°F, 20 to 25 minutes.',
    'Move the chicken to a plate. Simmer the pan juices with the mustard for 3 minutes, stir in the cream, and cook 1 minute more. Spoon over the chicken and finish with thyme.'] },
{ id: 'shawarma-chicken', name: 'Grilled Chicken with Yogurt & Shawarma Spices', course: 'Mains', serves: '6', page: 93, img: '0542', ingredients: [
  ['sweet paprika', 1, 'tsp', '1 teaspoon sweet paprika'],
  ['ground cumin', 1, 'tsp', '1 teaspoon ground cumin'],
  ['ground coriander', 0.5, 'tsp', '½ teaspoon ground coriander'],
  ['ground ginger', 0.5, 'tsp', '½ teaspoon ground ginger'],
  ['turmeric', 0.5, 'tsp', '½ teaspoon ground turmeric'],
  ['allspice', 0.25, 'tsp', '¼ teaspoon ground allspice'],
  ['cinnamon', 0.25, 'tsp', '¼ teaspoon ground cinnamon'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil, plus more for the grill'],
  ['whole-milk yogurt', 2.5, 'cup', '1½ cups plain whole-milk yogurt (plus 1 cup for the sauce)'],
  ['yellow onion', 0.25, '', '¼ cup minced yellow onion'],
  ['garlic', 2.5, 'clove', '2 garlic cloves, grated (plus ½ clove for the sauce)'],
  ['chicken (boneless breasts/thighs)', 3, 'lb', '3 pounds boneless, skinless chicken breasts and/or thighs'],
  ['tahini', 2, 'tbsp', '2 tablespoons tahini (sauce)'],
  ['lemon', 1, '', '1 tablespoon lemon juice (sauce), plus half a lemon for serving'],
  ['parsley', 0.25, 'bunch', 'Fresh parsley or mint leaves, for serving']],
  steps: ['Make the marinade: combine the spices, 2 teaspoons salt, and ½ teaspoon pepper. Whisk in the oil, then the yogurt, onion, and garlic.',
    'Pat the chicken dry. Halve large breasts crosswise and pound everything to an even ½ to ¾ inch thickness.',
    'Toss the chicken in the marinade, cover, and refrigerate for at least 3 hours or up to 24.',
    'Make the sauce: mix 1 cup yogurt, the tahini, lemon juice, half a garlic clove, and ¼ teaspoon salt. Refrigerate.',
    'Let the chicken sit at room temperature for 30 minutes. Heat a grill to medium-high, oil the grates, and grill until cooked through, 6 to 8 minutes per side.',
    'Rest for 10 minutes, sprinkle with salt, squeeze the lemon over, garnish with herbs, and serve with the sauce.'] },
{ id: 'bbq-chicken', name: 'Spicy Barbecue Pulled Chicken Sandwiches', course: 'Mains', serves: '6', page: 96, img: null, ingredients: [
  ['chicken thighs', 2, 'lb', '2 pounds bone-in, skin-on chicken thighs (4 to 6)'],
  ['chicken breasts', 2, 'lb', '2 pounds bone-in, skin-on chicken breasts (2 to 4)'],
  ['sweet paprika', 1.5, 'tsp', '1 teaspoon sweet paprika (plus ½ teaspoon for the sauce)'],
  ['ground cumin', 0.5, 'tsp', '½ teaspoon ground cumin, plus a pinch for the sauce'],
  ['cayenne', 0.5, 'tsp', '½ teaspoon cayenne pepper'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['olive oil', 0.25, 'cup', '¼ cup plus 2 tablespoons extra-virgin olive oil'],
  ['shallot', 2, '', '½ cup minced shallots'],
  ['stout beer', 12, 'oz', '1 (12-ounce) bottle stout beer, such as Guinness'],
  ['cider vinegar', 0.25, 'cup', '¼ cup cider vinegar'],
  ['worcestershire', 0.25, 'cup', '¼ cup Worcestershire sauce'],
  ['tomato paste', 0.5, 'cup', '½ cup tomato paste'],
  ['brown sugar', 0.25, 'cup', '¼ cup light or dark brown sugar'],
  ['honey', 3, 'tbsp', '3 tablespoons honey'],
  ['dijon mustard', 1, 'tbsp', '1 tablespoon Dijon mustard'],
  ['garlic', 2, 'clove', '2 garlic cloves, grated'],
  ['hamburger buns', 6, '', '6 hamburger buns'],
  ['pickles', 1, 'jar', 'Pickle slices, for serving']],
  steps: ['Heat the oven to 375°F. Pat the chicken dry and arrange skin-side up on a sheet pan.',
    'Mix the paprika, cumin, cayenne, 2 teaspoons salt, and 1 teaspoon pepper. Whisk in ¼ cup oil and toss with the chicken.',
    'Roast until the thighs and breasts reach 165°F, 35 to 45 minutes. Cool, reserving the pan drippings.',
    'For the sauce, cook the shallots in 2 tablespoons oil until tender. Add the beer, vinegar, Worcestershire, tomato paste, brown sugar, honey, mustard, garlic, 1 teaspoon salt, pepper, paprika, and cumin. Simmer until thickened, 25 to 30 minutes.',
    'Shred the chicken, discarding skin and bones, and toss with a few spoonfuls of drippings and the sauce.',
    'Serve on buns with coleslaw and pickles.'] },
{ id: 'white-bolognese', name: 'Orecchiette with White Bolognese', course: 'Mains', serves: '4 to 6', page: 101, img: '0545', ingredients: [
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['pancetta', 4, 'oz', '4 ounces cubed pancetta'],
  ['cremini mushrooms', 8, 'oz', '8 ounces cremini mushrooms, ½-inch diced'],
  ['butter', 2, 'tbsp', '2 tablespoons unsalted butter'],
  ['yellow onion', 1, '', '1 medium yellow onion, chopped'],
  ['carrots', 0.5, 'lb', '1½ cups diced carrots (2 to 3 medium)'],
  ['celery', 0.25, 'bunch', '1 cup diced celery (about 2 ribs)'],
  ['fennel seeds', 1, 'tsp', '1 teaspoon fennel seeds'],
  ['dried oregano', 1, 'tsp', '1 teaspoon dried oregano'],
  ['red pepper flakes', 0.25, 'tsp', '¼ teaspoon crushed red pepper flakes, plus more'],
  ['garlic', 4, 'clove', '2 tablespoons minced garlic (4 large cloves)'],
  ['ground pork', 1, 'lb', '1 pound ground pork'],
  ['white wine', 1, 'cup', '1 cup dry white wine, such as Pinot Grigio'],
  ['chicken broth', 1, 'cup', '1 cup low-sodium chicken broth or water'],
  ['heavy cream', 0.5, 'cup', '½ cup heavy cream'],
  ['orecchiette', 1, 'lb', '1 pound orecchiette pasta'],
  ['parmesan', 1, 'oz', 'Grated Parmesan cheese, for serving'],
  ['parsley', 0.25, 'bunch', '¼ cup chopped fresh parsley']],
  steps: ['Bring a large pot of salted water to a boil.',
    'In a 10-inch Dutch oven over medium heat, cook the pancetta until browned, 3 to 5 minutes.',
    'Add the mushrooms and cook until their liquid evaporates, about 3 minutes. Add the butter, onion, carrots, celery, fennel seeds, oregano, and pepper flakes and cook until tender, 6 to 8 minutes. Add the garlic for 1 minute.',
    'Add the pork, 2 teaspoons salt, and ¼ teaspoon pepper and cook, breaking it up, until browned, about 4 minutes.',
    'Add the wine and simmer, scraping up the browned bits. Add the broth and cream and simmer until slightly reduced, about 15 minutes.',
    'Cook the pasta until al dente. Reserve 1 cup pasta water, drain, and toss the pasta with the sauce, adding pasta water as needed.',
    'Serve with Parmesan and parsley.'] },
{ id: 'skirt-steak', name: 'Grilled Skirt Steak with Romesco Salsa', course: 'Mains', serves: '6', page: 102, img: '0546', ingredients: [
  ['skirt steak', 2, 'lb', '2 pounds skirt steak'],
  ['olive oil', 0.33, 'cup', '¼ cup extra-virgin olive oil (plus 1 tablespoon for the salsa)'],
  ['red wine vinegar', 3, 'tbsp', '2 tablespoons red wine vinegar (plus 1 tablespoon for the salsa)'],
  ['garlic', 5, 'clove', '3 garlic cloves, minced (plus 2 for the salsa)'],
  ['brown sugar', 2, 'tsp', '2 teaspoons light brown sugar'],
  ['cayenne', 0.25, 'tsp', '¼ teaspoon cayenne pepper'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['almonds', 0.25, 'cup', '¼ cup raw almonds, coarsely chopped'],
  ['cherry tomatoes', 0.5, 'pint', '1 cup cherry tomatoes, chopped'],
  ['roasted red peppers', 1, 'cup', '1 cup jarred roasted red peppers, drained and chopped'],
  ['parsley', 0.25, 'bunch', '¼ cup chopped fresh parsley'],
  ['smoked paprika', 0.25, 'tsp', '¼ teaspoon smoked paprika']],
  steps: ['Cut the steak into 6- to 8-inch pieces. Whisk the oil, vinegar, garlic, brown sugar, cayenne, 1 teaspoon salt, and ½ teaspoon pepper, add the steak, and refrigerate for 3 to 24 hours.',
    'Take the steak out 30 minutes before cooking.',
    'For the salsa, toast the almonds in the oil over medium-low until golden, about 3 minutes, then cool.',
    'Combine the tomatoes, roasted peppers, vinegar, parsley, garlic, paprika, and salt.',
    'Grill the steak over medium-high heat, 3 to 5 minutes per side for medium-rare. Rest for 10 minutes.',
    'Drain most of the liquid from the salsa, stir in the almonds, slice the steak against the grain, and top with the salsa.'] },

// ---------- Seafood ----------
{ id: 'shrimp-vodka', name: 'Saucy Shrimp alla Vodka', course: 'Seafood', serves: '4', page: 118, img: '0547', ingredients: [
  ['butter', 2, 'tbsp', '2 tablespoons unsalted butter or extra-virgin olive oil'],
  ['shallot', 2, '', '2 medium shallots, chopped (½ cup)'],
  ['garlic', 2, 'clove', '1 tablespoon minced garlic (2 large cloves)'],
  ['dried oregano', 0.5, 'tsp', '½ teaspoon dried oregano'],
  ['red pepper flakes', 0.25, 'tsp', '¼ teaspoon crushed red pepper flakes, plus more'],
  ['vodka', 0.6, 'cup', '½ cup plus 1 tablespoon vodka, divided'],
  ['tomato paste', 2, 'tbsp', '2 tablespoons tomato paste'],
  ['crushed tomatoes', 1, 'can', '1 (15-ounce) can crushed tomatoes'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['shrimp', 1, 'lb', '1 pound shrimp (16/20 count), peeled and deveined'],
  ['heavy cream', 0.25, 'cup', '¼ cup heavy cream'],
  ['parmesan', 1.5, 'oz', '½ cup grated Parmesan cheese'],
  ['parsley', 0.25, 'bunch', 'Chopped fresh parsley, for serving'],
  ['crusty bread', 1, 'loaf', 'Crusty bread, for serving']],
  steps: ['In a 12-inch skillet, melt the butter over medium-low. Cook the shallots until translucent, 3 to 5 minutes. Add the garlic, oregano, and pepper flakes for 1 minute.',
    'Add the tomato paste and cook until it darkens, 2 to 3 minutes.',
    'Raise the heat to medium, add ½ cup vodka, and cook until almost evaporated. Add the tomatoes, 1 teaspoon salt, and pepper and simmer until thick, 10 to 12 minutes.',
    'Pat the shrimp dry, season, and add to the sauce. Cook until just opaque, about 3 minutes. Stir in the cream and simmer 1 minute.',
    'Off the heat, stir in the last tablespoon of vodka and the Parmesan. Sprinkle with parsley and serve with bread.'] },
{ id: 'roasted-fish', name: 'Roasted Fish with Green Herbs, Lemon & Olives', course: 'Seafood', serves: '4', page: 121, img: '0548', ingredients: [
  ['halibut', 1.5, 'lb', '4 skinless halibut fillets (6 ounces each), at least 1 inch thick'],
  ['olive oil', 0.33, 'cup', '⅓ cup extra-virgin olive oil, plus more for drizzling'],
  ['tarragon', 0.5, 'bunch', '3 tablespoons minced fresh tarragon'],
  ['chives', 0.5, 'bunch', '3 tablespoons minced fresh chives'],
  ['thyme', 0.5, 'bunch', '1 tablespoon chopped fresh thyme leaves'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['lemon', 1, '', '1 lemon'],
  ['castelvetrano olives', 0.5, 'cup', '½ cup pitted Castelvetrano or other green olives']],
  steps: ['Heat the oven to 400°F. Pat the fish dry.',
    'Whisk the oil, tarragon, chives, thyme, 1½ teaspoons salt, and pepper. Grate in the lemon zest, then cut the lemon into quarters.',
    'Drizzle a baking dish with oil, add the fish, olives, and lemon quarters, and brush the herb oil over the fish.',
    'Roast until the fish flakes easily, 18 to 22 minutes. Press the lemons to release their juice and spoon the pan juices over the fish.',
    'Serve with the olives and a sprinkle of salt.'] },
{ id: 'chili-salmon', name: 'Salmon with Honey & Chili Crunch', course: 'Seafood', serves: '2', page: 122, img: '0549', ingredients: [
  ['salmon', 0.75, 'lb', '2 skinless salmon fillets (6 ounces each)'],
  ['salt', null, '', 'Kosher salt'],
  ['chili crunch', 1, 'tbsp', '1 tablespoon chili crunch or chili crisp'],
  ['seasoned rice vinegar', 1, 'tsp', '1 teaspoon rice vinegar'],
  ['honey', 1, 'tbsp', '1 tablespoon honey']],
  steps: ['Heat the oven to 375°F and line a sheet pan with parchment.',
    'Pat the salmon dry, sprinkle with salt, and place on the pan.',
    'Whisk the chili crunch and vinegar, then the honey. Brush the glaze over the salmon.',
    'Roast until the salmon flakes at the edges, 12 to 14 minutes. Spoon any glaze from the pan over the fish.'] },
{ id: 'clams', name: 'Littleneck Clams with Cherry Tomatoes & Pearl Couscous', course: 'Seafood', serves: '3 to 4', page: 125, img: '0550', ingredients: [
  ['clams', 3, 'lb', '3 pounds littleneck clams'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['shallot', 2, '', '2 large shallots, chopped (about ¾ cup)'],
  ['garlic', 4, 'clove', '4 garlic cloves, minced'],
  ['fresno chile', 1, '', '1 small red chile, such as Fresno, seeded and minced'],
  ['cherry tomatoes', 1.5, 'pint', '1 pint Sungold tomatoes plus 1 cup red cherry tomatoes'],
  ['white wine', 0.5, 'cup', '½ cup dry white wine, such as Sauvignon Blanc'],
  ['pearl couscous', 0.5, 'cup', '½ cup pearl couscous or fregola'],
  ['parsley', 0.25, 'bunch', '2 tablespoons chopped fresh parsley'],
  ['crusty bread', 1, 'loaf', 'Crusty bread, for serving']],
  steps: ['Soak the clams in salted cold water for 30 minutes, then lift them out and rinse.',
    'In a large Dutch oven, cook the shallots in the oil until tender, 3 to 5 minutes. Add the garlic and chile for 1 minute.',
    'Add the tomatoes, ½ teaspoon salt, and pepper and cook until they begin to collapse, 6 to 8 minutes.',
    'Add the wine and bring to a boil. Add the clams, cover, and cook until they open, 8 to 12 minutes, moving opened clams to a bowl.',
    'Add the couscous to the pot and simmer until tender, 10 to 15 minutes. Spoon over the clams, garnish with parsley, and serve with bread.'] },
{ id: 'slow-salmon', name: 'Slow-Roasted Salmon with Lemony Leeks & Asparagus', course: 'Seafood', serves: '6', page: 126, img: '0551', ingredients: [
  ['leeks', 2, '', '2 medium leeks, dark green leaves trimmed'],
  ['lemon', 2, '', '1 lemon, very thinly sliced, plus grated zest for serving'],
  ['olive oil', 5, 'tbsp', '5 tablespoons extra-virgin olive oil, divided'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['salmon', 2, 'lb', '2-pound salmon fillet, skin removed'],
  ['asparagus', 1, 'lb', '1 pound asparagus, trimmed and cut into 2-inch pieces'],
  ['flaky salt', null, '', 'Flaky sea salt'],
  ['dill', 0.25, 'bunch', 'Fresh dill, for serving']],
  steps: ['Heat the oven to 325°F.',
    'Slice the leeks into ¼-inch rounds, wash well, and pat dry. Spread on a sheet pan with the lemon slices, 2 tablespoons oil, and ½ teaspoon salt.',
    'Roast until the leeks are tender and lightly caramelized, about 30 minutes.',
    'Add the asparagus with another tablespoon of oil and push the vegetables to the edges. Place the salmon in the center, rub with the remaining oil, and season.',
    'Roast until the salmon reaches 120 to 125°F, 15 to 25 minutes. Finish with flaky salt, dill, and lemon zest.'] },

// ---------- Veggie Mains ----------
{ id: 'stuffed-squash', name: 'Cheesy Stuffed Squash with Kale & Brown Rice', course: 'Veggie Mains', serves: '4 to 6', page: 137, img: '0552', ingredients: [
  ['honeynut squash', 4, '', '4 honeynut squash (about 12 ounces each) or 3 delicata'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil, divided'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['yellow onion', 1, '', '1 cup chopped yellow onion'],
  ['garlic', 4, 'clove', '4 garlic cloves, minced'],
  ['sage', 0.5, 'bunch', '3 tablespoons chopped fresh sage'],
  ['red pepper flakes', 0.25, 'tsp', '¼ teaspoon crushed red pepper flakes'],
  ['white wine', 0.5, 'cup', '½ cup dry white wine'],
  ['kale', 0.5, 'bunch', '3 cups chopped kale leaves'],
  ['brown rice', 0.5, 'cup', '1½ cups cooked brown rice (about ½ cup uncooked)'],
  ['fontina', 6, 'oz', '1½ cups grated Fontina Val d\'Aosta (6 ounces), divided'],
  ['pecorino', 1.5, 'oz', '½ cup grated pecorino cheese, divided'],
  ['nutmeg', null, '', 'Freshly grated nutmeg (optional)']],
  steps: ['Heat the oven to 400°F and line a sheet pan with parchment.',
    'Halve the squash lengthwise and scoop out the seeds. Brush with 1 tablespoon oil, season, and roast cut-side down until tender, 20 to 25 minutes.',
    'Cook the onion in the remaining oil until tender, 3 to 6 minutes. Add the garlic, sage, and pepper flakes for 1 minute. Add the wine and reduce, then the kale until wilted. Stir in the rice.',
    'Scoop the squash flesh into the skillet, leaving a thin border in the shells, and mix. Let cool slightly.',
    'Stir in half the Fontina and pecorino. Fill the squash, top with the rest of the cheese, and bake until browned, 15 to 20 minutes. Grate nutmeg over the top.'] },
{ id: 'corn-pesto', name: 'Spaghetti with Sweet Corn Pesto', course: 'Veggie Mains', serves: '4 to 6', page: 138, img: '0553', ingredients: [
  ['olive oil', 7, 'tbsp', '7 tablespoons extra-virgin olive oil, divided'],
  ['panko', 0.5, 'cup', '½ cup panko bread crumbs'],
  ['red pepper flakes', 0.25, 'tsp', '¼ teaspoon crushed red pepper flakes'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['corn', 6, 'ear', '4 cups fresh corn kernels (from 5 to 7 ears)'],
  ['garlic', 2, 'clove', '2 garlic cloves, smashed and peeled'],
  ['parmesan', 1.5, 'oz', '½ cup grated Parmesan cheese'],
  ['spaghetti', 1, 'lb', '1 pound spaghetti'],
  ['cherry tomatoes', 2, 'pint', '2 pints cherry tomatoes, halved'],
  ['basil', 1, 'bunch', '1 cup fresh basil leaves, torn, divided'],
  ['lemon', 0.5, '', 'Grated lemon zest, for serving (optional)']],
  steps: ['Toast the panko in 1 tablespoon oil with the pepper flakes and a pinch of salt until golden, 3 to 5 minutes. Set aside.',
    'Bring a large pot of salted water to a boil.',
    'In the same skillet, cook the corn and garlic in 3 tablespoons oil with 1 teaspoon salt until tender, 4 to 6 minutes. Set aside ½ cup corn.',
    'Purée the rest of the corn and garlic with 1¼ teaspoons salt and ½ teaspoon pepper, drizzling in 3 tablespoons oil. Add the Parmesan.',
    'Cook the spaghetti until al dente, reserving 1 cup pasta water. Toss with the pesto, tomatoes, reserved corn, and half the basil, loosening with pasta water.',
    'Top with the remaining basil, lemon zest, and half the bread crumbs. Pass the rest at the table.'] },
{ id: 'red-curry-lentils', name: 'Red Curry Lentils with Sweet Potatoes & Spinach', course: 'Veggie Mains', serves: '4', page: 141, img: '0554', ingredients: [
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil, divided'],
  ['sweet potatoes', 1, 'lb', '1 pound sweet potatoes (about 2 medium), ¾-inch diced'],
  ['yellow onion', 1, '', '1 medium yellow onion, chopped'],
  ['garlic', 2, 'clove', '1 tablespoon minced garlic (2 large cloves)'],
  ['ginger', 1, 'knob', '1 tablespoon grated fresh ginger (about a 1-inch knob)'],
  ['red curry paste', 3, 'tbsp', '3 tablespoons Thai red curry paste'],
  ['fresno chile', 1, '', '1 small chile pepper, such as Fresno or serrano, minced'],
  ['turmeric', 1, 'tsp', '1 teaspoon ground turmeric'],
  ['red lentils', 1, 'cup', '1 cup red lentils, rinsed'],
  ['vegetable broth', 4, 'cup', '4 cups (1 quart) low-sodium vegetable broth'],
  ['salt', null, '', '2 teaspoons kosher salt, plus more'],
  ['coconut milk', 1, 'can', '1 (13-ounce) can full-fat coconut milk'],
  ['baby spinach', 5, 'oz', '1 (4- to 5-ounce) bag baby spinach'],
  ['lime', 0.5, '', 'Juice of half a lime'],
  ['white rice', 1, 'cup', 'Cooked rice, for serving (optional)'],
  ['cilantro', 0.25, 'bunch', 'Fresh cilantro leaves, for serving'],
  ['coconut flakes', 0.25, 'cup', 'Toasted unsweetened coconut flakes (optional)']],
  steps: ['In a Dutch oven, heat 2 tablespoons oil over medium-high. Brown the sweet potatoes, 5 to 7 minutes (they won\'t be cooked through). Set aside.',
    'Reduce the heat, add the remaining oil and the onion, and cook until translucent, 4 to 6 minutes. Add the garlic, ginger, curry paste, chile, and turmeric for 1 minute.',
    'Add the lentils, broth, salt, and the sweet potatoes. Simmer until the lentils are tender, 20 to 25 minutes.',
    'Add the coconut milk and simmer until creamy, 15 to 20 minutes.',
    'Stir in the spinach until wilted, then the lime juice. Serve over rice with cilantro and coconut.'] },
{ id: 'cauliflower-cakes', name: 'Crispy Cauliflower & Chickpea Cakes with Moroccan Spices', course: 'Veggie Mains', serves: '4', page: 142, img: '0555', ingredients: [
  ['cauliflower', 1, 'head', '1 medium head cauliflower (about 2 pounds)'],
  ['yellow onion', 1, '', '1 small yellow onion, sliced into ½-inch rings'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['chickpeas', 1, 'can', '1 (15-ounce) can chickpeas, rinsed and drained'],
  ['garlic', 2, 'clove', '2 medium garlic cloves, coarsely chopped'],
  ['harissa', 0.33, 'cup', '4 tablespoons harissa sauce, plus more for serving'],
  ['parsley', 0.25, 'bunch', '3 tablespoons chopped fresh parsley'],
  ['brown sugar', 2, 'tsp', '2 teaspoons light brown sugar'],
  ['sweet paprika', 1, 'tsp', '1 teaspoon sweet paprika'],
  ['ground cumin', 0.5, 'tsp', '½ teaspoon ground cumin'],
  ['ground ginger', 0.5, 'tsp', '½ teaspoon ground ginger'],
  ['cinnamon', 0.25, 'tsp', '¼ teaspoon ground cinnamon'],
  ['chickpea flour', 1, 'cup', '1 cup chickpea flour, divided'],
  ['neutral oil', null, '', 'Neutral oil, such as canola, for pan-frying'],
  ['whole-milk yogurt', 1, 'cup', '1 cup plain whole-milk yogurt, seasoned with ¼ teaspoon salt']],
  steps: ['Heat the oven to 400°F. Cut the cauliflower into 1-inch florets and roast with the onion, oil, and 1 teaspoon salt until tender and browned, 30 to 35 minutes. Cool.',
    'Pulse the chickpeas, garlic, and 3 tablespoons harissa in a food processor until coarse. Transfer to a bowl.',
    'Pulse the roasted cauliflower and onion until finely chopped but not puréed, and add to the chickpeas.',
    'Mix in the remaining harissa, parsley, brown sugar, spices, 1 teaspoon salt, pepper, and ½ cup chickpea flour.',
    'Shape into ⅓-cup patties about 1 inch thick and dredge in the remaining chickpea flour.',
    'Fry in batches in 3 tablespoons canola oil over medium-high, pressing to ½ inch thick, 1 to 2 minutes per side. Drain, salt, and serve with harissa and salted yogurt.'] },

// ---------- Sides ----------
{ id: 'garlic-greens', name: 'Side of Greens with Garlic & Soy', course: 'Sides', serves: '2 to 4', page: 150, img: '0557', ingredients: [
  ['kale', 2, 'bunch', '1 pound kale, Swiss chard, collards, or a mix (2 medium bunches)'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['garlic', 2, 'clove', '2 medium garlic cloves, minced'],
  ['red pepper flakes', null, '', 'Pinch of crushed red pepper flakes'],
  ['salt', null, '', '¼ teaspoon kosher salt'],
  ['soy sauce', 0.5, 'tsp', '½ teaspoon soy sauce or tamari']],
  steps: ['Bring a large pot of water to a boil.',
    'Trim any tough stems from the greens, chop coarsely, and rinse well.',
    'Blanch the greens until wilted, 2 to 3 minutes, then drain.',
    'In a 12-inch skillet, heat the oil, garlic, and pepper flakes over medium-low until fragrant, 1 to 2 minutes.',
    'Add the greens and salt and cook, tossing, until tender, 3 to 5 minutes. Off the heat, add the soy sauce and toss.'] },
{ id: 'maple-squash', name: 'Maple-Roasted Squash with Grapes, Shallots & Rosemary', course: 'Sides', serves: '4', page: 153, img: '0558', ingredients: [
  ['delicata squash', 2, '', '2 small delicata squash (about 1½ pounds total)'],
  ['red grapes', 1.5, 'cup', '1½ cups seedless red grapes, stems removed'],
  ['shallot', 3, '', '3 medium shallots, sliced ¼ inch thick'],
  ['rosemary', 0.5, 'bunch', '2 fresh rosemary sprigs'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['maple syrup', 1, 'tbsp', '1 tablespoon maple syrup'],
  ['cider vinegar', 1, 'tbsp', '1 tablespoon apple cider vinegar']],
  steps: ['Heat the oven to 425°F.',
    'Halve the squash lengthwise, scoop out the seeds, and slice into ½-inch half-moons. Spread on a sheet pan with the grapes, shallots, and rosemary.',
    'Drizzle with the oil, season with ½ teaspoon salt and pepper, and roast for 30 minutes, tossing once.',
    'Drizzle with the maple syrup and roast until caramelized, about 5 minutes. Immediately add the vinegar and toss, scraping up the browned bits.',
    'Sprinkle with salt and serve warm or at room temperature.'] },
{ id: 'herbed-farro', name: 'Warm Herbed Farro', course: 'Sides', serves: '6 to 8', page: 154, img: '0560', ingredients: [
  ['butter', 3, 'tbsp', '3 tablespoons unsalted butter or extra-virgin olive oil'],
  ['yellow onion', 1, '', '1 large yellow onion, chopped (about 1½ cups)'],
  ['thyme', 0.25, 'bunch', '1½ teaspoons chopped fresh thyme leaves'],
  ['chicken broth', 4, 'cup', '4 cups (1 quart) low-sodium chicken or vegetable broth'],
  ['farro', 2, 'cup', '2 cups whole-grain farro, rinsed'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['parsley', 0.5, 'bunch', '½ cup chopped fresh parsley'],
  ['scallions', 3, '', '½ cup minced scallions (2 to 3 scallions)']],
  steps: ['In a large saucepan, melt the butter over medium-low. Cook the onion and thyme until translucent, 6 to 8 minutes.',
    'Add the broth, farro, 2 teaspoons salt, and ½ teaspoon pepper and bring to a boil. Cover and simmer until al dente, 35 to 40 minutes.',
    'Add the parsley and scallions and simmer uncovered until the liquid is absorbed, 5 to 10 minutes. Taste for seasoning and serve warm.'] },
{ id: 'green-beans', name: 'Green Beans with Crispy Capers & Garlic', course: 'Sides', serves: '4', page: 157, img: '0561', ingredients: [
  ['salt', null, '', 'Kosher salt'],
  ['green beans', 1, 'lb', '1 pound green beans or haricots verts, trimmed'],
  ['olive oil', 2, 'tbsp', '2 tablespoons extra-virgin olive oil'],
  ['capers', 3, 'tbsp', '3 tablespoons capers, drained and patted dry'],
  ['garlic', 2, 'clove', '1 tablespoon chopped garlic'],
  ['lemon', 0.5, '', 'Juice of half a lemon, for serving']],
  steps: ['Blanch the beans in salted boiling water until bright green and crisp-tender, 2 to 5 minutes. Transfer to ice water, then drain and dry.',
    'Heat the oil in a large skillet over medium-high. Fry the capers until crispy, about 2 minutes, and drain on paper towels.',
    'Lower the heat to medium. Add the garlic, beans, and ¼ teaspoon salt and cook until the beans are hot and the garlic is just golden, about 2 minutes.',
    'Squeeze the lemon over, top with the capers, and serve.'] },
{ id: 'braised-cabbage', name: 'Braised Green Cabbage with Bacon & Caraway Seeds', course: 'Sides', serves: '6', page: 158, img: '0562', ingredients: [
  ['bacon', 4, 'slice', '4 slices bacon, cut into ½-inch pieces'],
  ['caraway seeds', 1, 'tsp', '1 teaspoon caraway seeds'],
  ['apple cider', 0.5, 'cup', '½ cup apple cider or apple juice'],
  ['green cabbage', 0.5, 'head', 'Half a large head green cabbage, cored and thinly sliced (about 10 cups)'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['apples', 1, '', '1 crisp apple, such as Fuji, cored and thinly sliced'],
  ['cider vinegar', 2, 'tbsp', '2 tablespoons apple cider vinegar']],
  steps: ['In a 12-inch skillet over medium heat, cook the bacon until crisp, 5 to 7 minutes. Set aside.',
    'Toast the caraway in the fat for 30 seconds. Carefully add the cider and scrape up the browned bits. Add half the cabbage, 1 teaspoon salt, and pepper and cook until wilted.',
    'Add the rest of the cabbage and the apple. Cook until tender and browned in spots, 15 to 20 minutes.',
    'Off the heat, toss with the vinegar and the bacon. Taste and serve.'] },
{ id: 'cucumber-salad', name: 'Crunchy Cucumber Salad with Peanuts & Chili Flakes', course: 'Sides', serves: '6 to 8', page: 161, img: '0563', ingredients: [
  ['persian cucumbers', 2, 'lb', '2 pounds Persian or other small seedless cucumbers'],
  ['salt', null, '', '1 teaspoon kosher salt'],
  ['sesame oil', 2, 'tbsp', '2 tablespoons toasted sesame oil'],
  ['seasoned rice vinegar', 2, 'tbsp', '2 tablespoons seasoned rice vinegar'],
  ['neutral oil', null, '', '1 tablespoon peanut or grapeseed oil'],
  ['soy sauce', 2, 'tsp', '2 teaspoons soy sauce or tamari'],
  ['sugar', 1, 'tsp', '1 teaspoon sugar'],
  ['red pepper flakes', 0.25, 'tsp', '¼ teaspoon crushed red pepper flakes'],
  ['peanuts', 0.5, 'cup', '½ cup lightly salted roasted peanuts, very finely chopped'],
  ['cilantro', 0.25, 'bunch', 'Chopped fresh cilantro, for serving (optional)']],
  steps: ['Slice the cucumbers ¼ inch thick and toss with the salt in a colander. Let drain for 30 minutes, then pat dry.',
    'In a large bowl, whisk the sesame oil, vinegar, peanut oil, soy sauce, sugar, and pepper flakes.',
    'Toss in the cucumbers. Just before serving, add the peanuts and garnish with cilantro.'] },
{ id: 'polenta', name: 'Creamy Polenta', course: 'Sides', serves: '4 to 6', page: 162, img: '0564', ingredients: [
  ['salt', null, '', '2 teaspoons kosher salt, plus more'],
  ['cornmeal', 1, 'cup', '1 cup stone-ground or medium-grind yellow cornmeal'],
  ['whole milk', 0.5, 'cup', '½ cup whole milk'],
  ['butter', 3, 'tbsp', '3 tablespoons unsalted butter'],
  ['parmesan', 2.5, 'oz', '¾ cup grated Grana Padano or Parmesan (2½ ounces)'],
  ['black pepper', null, '', 'Freshly ground black pepper']],
  steps: ['In a large saucepan, bring 5 cups water and the salt to a boil. Whisking constantly, slowly sprinkle in the cornmeal and whisk for about 1 minute until it thickens.',
    'Reduce the heat to low and simmer uncovered, stirring and scraping occasionally, until very thick, about 25 minutes.',
    'Add the milk and butter, return to a simmer, and cook until thick again, 5 to 10 minutes.',
    'Off the heat, stir in the cheese and pepper. Rest for 10 minutes before serving.'] },
{ id: 'asparagus', name: 'Asparagus Vinaigrette', course: 'Sides', serves: '4', page: 165, img: '0565', ingredients: [
  ['asparagus', 1, 'lb', '1 pound asparagus'],
  ['olive oil', 4, 'tbsp', '4 tablespoons extra-virgin olive oil, divided'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['shallot', 0.25, '', '1 tablespoon minced shallot'],
  ['red wine vinegar', 2, 'tsp', '2 teaspoons red wine vinegar'],
  ['whole-grain mustard', 0.5, 'tsp', '½ teaspoon whole-grain mustard'],
  ['parsley', 0.1, 'bunch', '1 tablespoon minced fresh parsley'],
  ['sugar', null, '', 'Pinch of sugar']],
  steps: ['Heat the oven to 375°F.',
    'Trim the asparagus, toss with 2 tablespoons oil and ¼ teaspoon salt on a sheet pan, and roast until crisp-tender, 14 to 22 minutes.',
    'Whisk the remaining oil with the shallot, vinegar, mustard, parsley, sugar, salt, and pepper.',
    'Move the asparagus to a serving dish, pour the dressing over, and serve warm or at room temperature.'] },
{ id: 'cauliflower-sage', name: 'Roasted Cauliflower with Fried Sage & Hazelnuts', course: 'Sides', serves: '4', page: 166, img: '0566', ingredients: [
  ['cauliflower', 1, 'head', '1 large head cauliflower (about 2½ pounds)'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['butter', 3, 'tbsp', '3 tablespoons unsalted butter'],
  ['sage', 1, 'bunch', '½ cup packed fresh sage leaves'],
  ['hazelnuts', 0.5, 'cup', '½ cup whole raw hazelnuts, chopped'],
  ['nutmeg', null, '', 'Freshly grated nutmeg, for serving']],
  steps: ['Heat the oven to 425°F.',
    'Cut the cauliflower into 2-inch florets, toss with the oil, ¾ teaspoon salt, and pepper, and roast until tender and browned, 25 to 30 minutes.',
    'Melt the butter in a small skillet over medium. When it sizzles, add the sage and hazelnuts and cook until the butter is nutty and the nuts are toasted, about 3 minutes.',
    'Spoon the butter, sage, and hazelnuts over the cauliflower. Finish with salt and freshly grated nutmeg.'] },
{ id: 'ginger-rice', name: 'White Rice with Ginger & Leeks', course: 'Sides', serves: '4 to 6', page: 169, img: '0567', ingredients: [
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil, divided'],
  ['ginger', 1, 'knob', '2 tablespoons minced fresh ginger (from a 2-inch knob)'],
  ['white rice', 1.5, 'cup', '1½ cups long- or medium-grain white rice, rinsed'],
  ['salt', null, '', 'Kosher salt'],
  ['leeks', 1, '', '1 medium leek, trimmed'],
  ['lime', 0.5, '', 'Grated zest of half a lime (optional)']],
  steps: ['In a large saucepan, heat 1 tablespoon oil over medium. Add the ginger and cook until fragrant, about 30 seconds.',
    'Add the rice and 1 teaspoon salt and stir to coat. Add 2¼ cups water and bring to a boil. Cover and simmer on low for 15 minutes, then rest off the heat for 10.',
    'Halve the leek lengthwise and slice into half-moons. Rinse, dry, and cook in the remaining oil with ¼ teaspoon salt until tender but not browned, 7 to 10 minutes.',
    'Fold the leeks into the rice, season, and garnish with lime zest.'] },
{ id: 'coleslaw', name: 'Perfect Picnic Coleslaw', course: 'Sides', serves: '8 to 10', page: 170, img: '0568', ingredients: [
  ['green cabbage', 1, 'head', '1 small head green cabbage (2½ pounds)'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['kale', 0.5, 'bunch', '2 cups julienned Tuscan (lacinato) or curly kale'],
  ['carrots', 0.25, 'lb', '1 cup grated carrots (about 2 medium)'],
  ['scallions', 4, '', '¾ cup thinly sliced scallions (about 4)'],
  ['mayonnaise', 0.5, 'cup', '½ cup mayonnaise'],
  ['seasoned rice vinegar', 3, 'tbsp', '3 tablespoons seasoned rice vinegar'],
  ['dijon mustard', 1, 'tsp', '1 teaspoon Dijon mustard']],
  steps: ['Halve and core the cabbage and slice it into thin shreds (about 10 cups). Massage with 1 teaspoon salt for 30 seconds until slightly wilted.',
    'Add the kale, carrots, and scallions and toss.',
    'Whisk the mayonnaise, vinegar, mustard, 1 teaspoon salt, and ½ teaspoon pepper. Pour over the vegetables and toss well.',
    'Season to taste and serve at room temperature.'] },
{ id: 'broccolini', name: 'Roasted Broccolini with Pickled Pepperoncini', course: 'Sides', serves: '4 to 6', page: 173, img: '0569', ingredients: [
  ['broccolini', 3, 'bunch', '1½ pounds broccolini (3 to 4 bunches)'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['salt', null, '', 'Kosher salt'],
  ['pepperoncini', 0.33, 'cup', '⅓ cup coarsely chopped jarred pepperoncini'],
  ['parsley', 0.25, 'bunch', '¼ cup chopped fresh flat-leaf parsley'],
  ['red wine vinegar', 1, 'tbsp', '1 tablespoon red wine vinegar']],
  steps: ['Heat the oven to 400°F.',
    'Trim the broccolini and halve any thick stalks lengthwise. Toss with the oil and ½ teaspoon salt on a sheet pan.',
    'Roast until tender, 15 to 25 minutes, tossing once.',
    'Mix the pepperoncini, parsley, vinegar, and a pinch of salt. Spoon over the broccolini with its juices and serve.'] },
{ id: 'potato-salad', name: 'Potato and Chickpea Salad with Dill & Cornichons', course: 'Sides', serves: '6', page: 174, img: '0723', ingredients: [
  ['baby potatoes', 1.5, 'lb', '1½ pounds small red or baby Yukon Gold potatoes'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['olive oil', 0.25, 'cup', '¼ cup extra-virgin olive oil'],
  ['white wine vinegar', 1, 'tbsp', '1 tablespoon Champagne or white wine vinegar'],
  ['dijon mustard', 0.5, 'tsp', '½ teaspoon Dijon mustard'],
  ['chickpeas', 1, 'can', '1 (15-ounce) can chickpeas, rinsed and drained'],
  ['red onion', 0.5, '', '½ cup minced red onion (half a small onion)'],
  ['cornichons', 3.5, 'oz', '¼ cup finely chopped cornichons (about 3.5 ounces)'],
  ['mayonnaise', 2, 'tbsp', '2 tablespoons mayonnaise'],
  ['dill', 0.5, 'bunch', '½ cup minced fresh dill']],
  steps: ['Cover the potatoes with water, add 2 tablespoons salt, and boil until just tender, 15 to 20 minutes. Drain.',
    'Whisk the oil, vinegar, mustard, ½ teaspoon salt, and ¼ teaspoon pepper. Stir in the chickpeas and onion.',
    'Halve or quarter the warm potatoes and toss with the dressing. Let cool.',
    'Add the cornichons and mayonnaise, then the dill. Season and serve at room temperature.'] },
{ id: 'sweet-potatoes', name: 'Spiced Sweet Potatoes with Pecans & Pomegranate Seeds', course: 'Sides', serves: '4 to 6', page: 177, img: '0724', ingredients: [
  ['sweet potatoes', 2.5, 'lb', '2½ pounds sweet potatoes (3 to 4 medium)'],
  ['rosemary', 0.5, 'bunch', '2 fresh rosemary sprigs'],
  ['olive oil', 4, 'tbsp', '4 tablespoons extra-virgin olive oil'],
  ['cinnamon', 0.5, 'tsp', '½ teaspoon ground cinnamon'],
  ['chipotle powder', 0.5, 'tsp', '½ teaspoon chipotle chile powder'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['pecans', 0.75, 'cup', '¾ cup pecans, coarsely chopped'],
  ['maple syrup', 2, 'tbsp', '2 tablespoons maple syrup'],
  ['pomegranate', 1, '', '½ cup pomegranate arils']],
  steps: ['Heat the oven to 425°F.',
    'Peel the sweet potatoes, cut into 1-inch pieces, and spread on a sheet pan with the rosemary.',
    'Whisk the oil, cinnamon, chipotle, 1 teaspoon salt, and ¼ teaspoon pepper. Toss with the potatoes.',
    'Roast until almost tender, 20 to 25 minutes, tossing once.',
    'Add the pecans and maple syrup, toss, and roast until tender, 5 to 10 minutes more.',
    'Discard the rosemary stems, add the pomegranate arils, and serve warm or at room temperature.'] },
{ id: 'grilled-zucchini', name: 'Grilled Zucchini with Charred Lemon Dressing, Feta & Mint', course: 'Sides', serves: '6', page: 178, img: '0725', ingredients: [
  ['zucchini', 4, '', '4 small-ish zucchini (6 to 8 inches long)'],
  ['olive oil', 4, 'tbsp', '4 tablespoons extra-virgin olive oil, divided, plus more'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['lemon', 0.5, '', 'Half a lemon'],
  ['honey', 0.5, 'tsp', '½ teaspoon honey'],
  ['ground cumin', 0.5, 'tsp', '½ teaspoon ground cumin'],
  ['feta', 3, 'oz', '3 ounces feta cheese, crumbled'],
  ['mint', 0.25, 'bunch', 'A small handful of fresh mint leaves']],
  steps: ['Heat a grill to medium-high.',
    'Slice the zucchini lengthwise into ½-inch planks, toss with 2 tablespoons oil, ½ teaspoon salt, and pepper.',
    'Grill until tender with good marks, 3 to 5 minutes per side. Grill the lemon half cut-side down until charred, about 3 minutes.',
    'Squeeze the lemon into a bowl and whisk with the remaining oil, honey, cumin, and ¼ teaspoon salt.',
    'Arrange the zucchini on a platter, pour the dressing over, and top with feta, torn mint, and pepper.'] },
{ id: 'smashed-potatoes', name: 'Crispy Smashed Potatoes with Salsa Verde', course: 'Sides', serves: '4', page: 181, img: '0726', ingredients: [
  ['baby potatoes', 2, 'lb', '2 pounds small Yukon Gold potatoes (about 1½ inches)'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['olive oil', 6, 'tbsp', '6 tablespoons extra-virgin olive oil, divided'],
  ['parsley', 0.25, 'bunch', '3 tablespoons chopped fresh parsley'],
  ['mint', 0.25, 'bunch', '2 tablespoons chopped fresh mint leaves'],
  ['capers', 2, 'tbsp', '2 tablespoons capers, drained and chopped'],
  ['scallions', 1, '', '2 tablespoons chopped scallion (about 1)'],
  ['garlic', 1, 'clove', '1 garlic clove, minced'],
  ['red wine vinegar', 2, 'tbsp', '2 tablespoons red wine or sherry vinegar']],
  steps: ['Cover the potatoes with water, add 2 tablespoons salt, and simmer until just tender, 10 to 15 minutes. Drain and let steam dry.',
    'Heat the oven to 450°F and brush a sheet pan with 1 tablespoon oil.',
    'Smash each potato to about ½ inch thick with the bottom of a glass. Drizzle with 3 tablespoons oil, season, and roast until golden and crisp, 30 to 40 minutes.',
    'Meanwhile, mix the parsley, mint, capers, scallion, garlic, vinegar, remaining oil, and ¼ teaspoon salt.',
    'Spoon the salsa verde over the potatoes and sprinkle with salt and pepper.'] },
{ id: 'creamed-corn', name: 'Coconut Creamed Corn', course: 'Sides', serves: '4 to 6', page: 182, img: '1016', ingredients: [
  ['coconut flakes', 0.5, 'cup', '½ cup unsweetened coconut flakes'],
  ['coconut milk', 1, 'can', '1 (13.5-ounce) can unsweetened full-fat coconut milk'],
  ['corn', 6, 'ear', '4 cups fresh corn kernels (about 5 to 7 ears)'],
  ['salt', null, '', '1 teaspoon kosher salt, plus more'],
  ['lime', 0.33, '', '2 teaspoons freshly squeezed lime juice'],
  ['chives', 1, 'bunch', '½ cup thinly sliced chives or scallions'],
  ['chipotle powder', 0.25, 'tsp', '¼ teaspoon chipotle chile powder']],
  steps: ['In a 12-inch skillet, toast the coconut flakes over medium heat until golden, 3 to 5 minutes. Set aside and wipe out the pan.',
    'Whisk the coconut milk in the skillet until smooth. Add the corn and salt and bring to a boil, then simmer until the milk has reduced and thickened, 20 to 25 minutes.',
    'Off the heat, stir in the lime juice, half the chives, and the chipotle.',
    'Garnish with the toasted coconut and remaining chives and serve right away.'] },
{ id: 'brussels', name: 'Brussels Sprouts with Dates & Crispy Prosciutto', course: 'Sides', serves: '4 to 6', page: 185, img: '1017', ingredients: [
  ['prosciutto', 1, 'oz', '1 ounce thinly sliced prosciutto'],
  ['brussels sprouts', 1.5, 'lb', '1½ pounds Brussels sprouts, trimmed and halved'],
  ['olive oil', 3, 'tbsp', '3 tablespoons extra-virgin olive oil'],
  ['salt', null, '', '½ teaspoon kosher salt'],
  ['dates', 0.33, 'cup', '⅓ cup chopped pitted dates'],
  ['balsamic vinegar', 1, 'tbsp', '1 tablespoon balsamic vinegar']],
  steps: ['Heat the oven to 400°F.',
    'Bake the prosciutto on a sheet pan until crisp, about 10 minutes. Set aside, keeping the pan.',
    'Toss the sprouts with the oil and salt on the pan, cut-sides down, and roast until tender and golden, 25 to 30 minutes, tossing once.',
    'Immediately add the dates and vinegar and toss. Crumble the prosciutto over the top and serve.'] },

// ---------- Brunch ----------
{ id: 'winter-fruit', name: 'Winter Fruit Salad', course: 'Brunch', serves: '6', page: 235, img: '1018', ingredients: [
  ['orange', 5, '', '2 pounds oranges, such as Cara Cara, navel, blood oranges, or a mix'],
  ['grapefruit', 1, '', '1 large ruby red grapefruit'],
  ['pear', 1, '', '1 ripe Anjou or other pear'],
  ['sugar', null, '', 'Pinch of granulated sugar'],
  ['salt', null, '', 'Pinch of kosher salt'],
  ['pomegranate', 0.33, '', '¼ cup pomegranate arils'],
  ['olive oil', 2, 'tsp', '2 teaspoons extra-virgin olive oil'],
  ['mint', 0.25, 'bunch', '3 tablespoons torn fresh mint leaves'],
  ['flaky salt', null, '', 'Flaky sea salt, for serving (optional)']],
  steps: ['With a serrated knife, peel the oranges and grapefruit, removing the pith. Slice into thin rounds and remove any seeds.',
    'Halve and core the pear and slice thinly.',
    'Toss the citrus with the sugar and salt. Arrange on a platter with the pear and any juices.',
    'Scatter the pomegranate on top, drizzle with the oil, and finish with mint and flaky salt.'] },
{ id: 'poblano-hash', name: 'Sweet Potato & Poblano Hash with Eggs', course: 'Veggie Mains', serves: '2 to 4', page: 241, img: '1019', ingredients: [
  ['olive oil', 4, 'tbsp', '4 tablespoons extra-virgin olive oil, divided'],
  ['sweet potatoes', 1.5, 'lb', '1½ pounds sweet potatoes, peeled and ½-inch diced'],
  ['poblano', 2, '', '1½ cups diced poblano pepper (about 2)'],
  ['yellow onion', 1, '', '1½ cups chopped yellow onion (1 medium)'],
  ['chipotle powder', 0.25, 'tsp', '¼ teaspoon chipotle chile powder'],
  ['ground cumin', 0.25, 'tsp', '¼ teaspoon ground cumin'],
  ['salt', null, '', '1 teaspoon kosher salt, plus more'],
  ['black pepper', null, '', 'Freshly ground black pepper'],
  ['garlic', 1, 'clove', '1 medium garlic clove, minced'],
  ['scallions', 2, '', '¼ cup thinly sliced scallions, divided'],
  ['white wine vinegar', 2, 'tsp', '2 teaspoons white wine vinegar'],
  ['eggs', 4, '', '4 large eggs'],
  ['goat cheese', 1, 'oz', '¼ cup crumbled Cotija or plain goat cheese'],
  ['avocado', 1, '', 'Sliced avocado and toast, for serving'],
  ['hot sauce', null, '', 'Hot sauce, for serving (optional)']],
  steps: ['Heat the oven to 375°F.',
    'In a 12-inch ovenproof skillet, heat 3 tablespoons oil over medium-high. Add the sweet potatoes in an even layer and cook, tossing occasionally, until lightly browned, 4 to 6 minutes.',
    'Add the remaining oil, poblanos, onion, chipotle, cumin, salt, and pepper. Cook until browned and tender, 6 to 8 minutes.',
    'Add the garlic and half the scallions for 1 minute. Off the heat, stir in the vinegar.',
    'Make 4 hollows, crack an egg into each, and season. Bake until the whites are just set, 5 to 7 minutes.',
    'Top with the cheese and remaining scallions. Serve with toast, avocado, and hot sauce.'] },
{ id: 'frittata', name: 'Red Potato & Leek Frittata with Goat Cheese & Dill', course: 'Veggie Mains', serves: '6 to 8', page: 245, img: '1020', ingredients: [
  ['butter', 1, 'tbsp', 'Softened unsalted butter, for the baking dish'],
  ['olive oil', 5, 'tbsp', '5 tablespoons olive oil, divided, plus more as needed'],
  ['red potatoes', 1, 'lb', '1 pound red potatoes (about 3 medium), ¼-inch diced'],
  ['salt', null, '', 'Kosher salt and freshly ground black pepper'],
  ['leeks', 2, '', '2 large leeks, halved lengthwise and sliced (about 4 cups)'],
  ['white wine vinegar', 2, 'tsp', '2 teaspoons white wine vinegar'],
  ['eggs', 12, '', '12 large eggs'],
  ['whole milk', 1, 'cup', '1 cup whole milk'],
  ['goat cheese', 4, 'oz', '1 (4-ounce) log plain goat cheese'],
  ['dill', 0.25, 'bunch', '2 tablespoons chopped fresh dill']],
  steps: ['Heat the oven to 350°F and generously butter a 9 × 13-inch baking dish.',
    'In a 12-inch skillet, heat 3 tablespoons oil over medium-high. Add the potatoes with ½ teaspoon salt and cook until tender and lightly browned, about 10 minutes. Spread in the baking dish.',
    'Lower the heat to medium, add the remaining oil and the leeks with salt and pepper, and cook until lightly caramelized, 7 to 9 minutes. Add the vinegar, scrape up the browned bits, and scatter over the potatoes.',
    'Whisk the eggs, milk, 1 teaspoon salt, and ½ teaspoon pepper and pour into the dish. Crumble the goat cheese over the top and sprinkle with dill.',
    'Bake until just set in the center, 25 to 30 minutes. Rest for 10 minutes before serving.'] },
];

// Aisle + pantry-staple flags for the grocery list
const AISLES = ['Produce', 'Herbs', 'Meat & Seafood', 'Dairy & Eggs', 'Bakery', 'Pantry', 'Spices', 'Bar'];
const ING = {};
const put = (cat, list, staple) => list.split('|').forEach(n => ING[n] = { cat, staple: !!staple });
put('Produce', 'lemon|lime|orange|grapefruit|garlic|shallot|yellow onion|red onion|scallions|jalapeño|fresno chile|poblano|ginger|cherry tomatoes|cucumber|persian cucumbers|bell pepper|golden beets|carrots|celery|kale|swiss chard|little gem lettuce|escarole|radicchio|romaine|arugula|baby spinach|radishes|fennel|green beans|asparagus|leeks|cauliflower|broccolini|green cabbage|eggplant|zucchini|sweet potatoes|baby potatoes|red potatoes|delicata squash|honeynut squash|brussels sprouts|corn|avocado|apples|pear|peaches|nectarines|cherries|melon|green grapes|red grapes|pomegranate|cremini mushrooms|dates');
put('Herbs', 'parsley|dill|mint|basil|cilantro|chives|thyme|rosemary|sage|tarragon');
put('Meat & Seafood', 'chicken thighs|chicken breasts|whole chicken|chicken (boneless breasts/thighs)|hot italian sausage|sweet italian sausage|bacon|pancetta|prosciutto|ground pork|skirt steak|shrimp|clams|crab|halibut|salmon');
put('Dairy & Eggs', 'eggs|butter|greek yogurt|whole-milk yogurt|heavy cream|whole milk|cream cheese|parmesan|pecorino|feta|goat cheese|mozzarella|halloumi|gouda|blue cheese|fontina|harbison cheese');
put('Bakery', 'baguette|crusty bread|pita|hamburger buns|cornbread');
put('Pantry', 'chickpeas|cannellini beans|crushed tomatoes|tomato paste|coconut milk|chicken broth|vegetable broth|green lentils|red lentils|farro|white rice|brown rice|pearl couscous|ditalini|orecchiette|spaghetti|panko|cornmeal|chickpea flour|tortilla chips|crackers|tahini|maple syrup|honey|dijon mustard|whole-grain mustard|mayonnaise|soy sauce|sesame oil|seasoned rice vinegar|red wine vinegar|white wine vinegar|cider vinegar|sherry vinegar|balsamic vinegar|worcestershire|red curry paste|chili crunch|harissa|capers|kalamata olives|castelvetrano olives|cornichons|pepperoncini|roasted red peppers|candied jalapeños|pickles|hot sauce|golden raisins|walnuts|pecans|almonds|marcona almonds|pistachios|hazelnuts|cashews|peanuts|sesame seeds|coconut flakes|brown sugar|sparkling water|coconut water|apple cider');
put('Spices', 'sweet paprika|smoked paprika|ground cumin|ground coriander|ground ginger|turmeric|allspice|cinnamon|cayenne|red pepper flakes|dried oregano|fennel seeds|caraway seeds|chipotle powder|old bay|nutmeg|pink peppercorns');
put('Bar', 'tequila|vodka|gin|dry vermouth|bourbon|campari|kirsch|white wine|champagne|stout beer|bitters');
put('Pantry', 'olive oil|neutral oil|salt|flaky salt|black pepper|sugar|ice|water', true);
